name: Ofuscar e Publicar no GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22 

    - name: Instalar o Ofuscador
      run: npm install -g javascript-obfuscator

    - name: Atualizar links (Cache Busting) no HTML e JavaScript
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)        
        
        sed -i -E "s/src=\"([^\/]+)\.js\"/src=\"dist\/\1.${SHORT_SHA}.js\"/g" index.html

        for f in *.js; do
          if [ -f "$f" ]; then
            sed -i -E "s/([\"'])\.?\/?([^\/]+)\.js([\"'])/\1\2.${SHORT_SHA}.js\3/g" "$f"
          fi
        done

    - name: Ofuscar e Renomear JS (Cache Busting)
      run: |
        mkdir -p dist/data
        
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        
        for f in *.js; do
          if [ -f "$f" ]; then
            filename="${f%.*}"
            javascript-obfuscator "$f" --output "dist/${filename}.${SHORT_SHA}.js" --compact true --control-flow-flattening true
          fi
        done

        for f in data/*.js; do
          if [ -f "$f" ]; then
            filename=$(basename "$f" .js)
            javascript-obfuscator "$f" --output "dist/data/${filename}.${SHORT_SHA}.js" --compact true --control-flow-flattening true
          fi
        done

    - name: Atualizar links no HTML
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)        
        
        sed -i -E "s/src=\"([^\/]+)\.js\"/src=\"dist\/\1.${SHORT_SHA}.js\"/g" index.html

    - name: Publicar no GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: . 
        branch: gh-pages
